### ISSUE TITLE
Feature Request: Can we enable loop and offline playing?

### ISSUE THREAD

**Issue by lszyba1** [fly-apps/live_beats#61]
Hello,
Is it possible to host live_beats, and upload the mp3, and then set it to play in loop, and at the same time exit the browser. 
Almost like a radio podcast. Any user can join and start listening to my mp3's. I would login tomorrow and set a new playlist. 

If there is a different place to discuss this please let me know.

Thanks
Lucas

**Comment by andreapavoni** [comment]
Hi there, I'm not involved in this project but I'm following/lurking it since the beginning, mostly because I have had a similar idea for 10+ years and when I've seen it implemented in Elixir/Phoenix I was very happy about it.

Considering that owning/uploading mp3's is way more rare nowadays, I've seen the _limits_ of this project (which remains and excellent work and example for many things about Phoenix).

If you want something similar to what you described, perhaps you need other tools which are tailored for this kind of needs. For example [icacast](https://icecast.org), or even [liquidsoap](https://www.liquidsoap.info).

I did a similar thing (first in Elixir/Phoenix, then in Rust): a web radio that plays 24h/7d and fetches the songs from a playlist I own on soundcloud. the backend just keeps track of the playlist and the current playing song, when one finishes, the next one is sent to clients through websockets. Users, regardless of when they joined, will listen the same song at the exact playback time as the other users, like a broadcast radio. When the playlist has been played, it reloads again from soundcloud (to get the updated one), shuffles the tracks and restarts. I can edit the songs from soundcloud, so no need for mantainance of the backend.

So, you can achieve something similar to what I did for your needs, but I'm not sure this project can help you, I mean, you should modify it so that it only supports one active user/playlist/show and keep the others as listeners. Also, the register/login mechanism will potentially allow everyone to join, not just your friends. I didn't checked how/where the uploaded mp3 are stored, but I suppose you will need some storage  to host them, and you might need to write code for that.

my 2 cents

**Comment by chrismccord** [comment]
We don't accept feature requests, but the app is MIT licensed if you'd like to make your own fork. Thanks!
